
#Each new term in the fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, then the first ten terms will be? by considering the terms in the fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms
#include <stdio.h>

int main() {
    
    const int LIMIT = 4000000;
   
    int a = 1, b = 2;
    int sum = 0;
    if (b % 2 == 0) {
        sum += b;
    }
    while (b <= LIMIT) {
        int next = a + b;
        a = b;
        b = next;
        if (b % 2 == 0 && b <= LIMIT) {
            sum += b;
        }
    }
    printf("Sum of even-valued Fibonacci terms not exceeding %d: %d\n", LIMIT, sum);

    return 0;
}
